# Generated by Django 3.2.12 on 2022-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_is_key_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False),
        ),
    ]
