# Generated by Django 3.2.12 on 2022-05-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testimonial_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
    ]
